"""Initial migration with enhanced models

Revision ID: 2ee0423e9a9e
Revises: 
Create Date: 2026-04-26 14:52:51.400645
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '2ee0423e9a9e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_workflows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_approval_levels', sa.JSON(), nullable=True),
    sa.Column('auto_approve_after_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'REJECT', 'SUBMIT', 'VIEW', name='auditaction'), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_tag_name', 'tags', ['name'], unique=False)
    op.create_index(op.f('ix_tags__version'), 'tags', ['_version'], unique=False)
    op.create_index(op.f('ix_tags_deleted_at'), 'tags', ['deleted_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oidc_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('workload', sa.String(length=255), nullable=True),
    sa.Column('workload_type', sa.Enum('WEB', 'API', 'DATABASE', 'STORAGE', 'COMPUTE', 'AI', 'DATA_PROCESSING', name='workloadtype'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_users__version'), 'users', ['_version'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_oidc_sub'), 'users', ['oidc_sub'], unique=True)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_workload', 'users', ['workload'], unique=False)
    op.create_table('firewall_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('landing_zone', sa.String(length=100), nullable=False),
    sa.Column('subscription_id', sa.String(length=100), nullable=True),
    sa.Column('resource_group', sa.String(length=255), nullable=True),
    sa.Column('firewall_policy', sa.String(length=255), nullable=True),
    sa.Column('rule_collection_name', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('ALLOW', 'DENY', 'ALERT', name='ruleaction'), nullable=False),
    sa.Column('source_addresses', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('destination_addresses', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('destination_ports', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('destination_fqdns', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('protocols', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('category', sa.Enum('NETWORK', 'SECURITY', 'APPLICATION', 'DATA', name='resourcecategory'), nullable=False),
    sa.Column('workload', sa.String(length=100), nullable=True),
    sa.Column('workload_type', sa.Enum('WEB', 'API', 'DATABASE', 'STORAGE', 'COMPUTE', 'AI', 'DATA_PROCESSING', name='workloadtype'), nullable=True),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'ACTIVE', 'DEPRECATED', 'ARCHIVED', name='rulestatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_for_approval_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint('priority >= 100 AND priority <= 10000', name='check_priority_range'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('name', 'landing_zone', name='uq_rule_name_zone')
    )
    op.create_index('idx_landing_zone_status', 'firewall_rules', ['landing_zone', 'status'], unique=False)
    op.create_index('idx_name_status', 'firewall_rules', ['name', 'status'], unique=False)
    op.create_index('idx_workload_environment', 'firewall_rules', ['workload', 'environment'], unique=False)
    op.create_index(op.f('ix_firewall_rules__version'), 'firewall_rules', ['_version'], unique=False)
    op.create_index(op.f('ix_firewall_rules_approved_by_id'), 'firewall_rules', ['approved_by_id'], unique=False)
    op.create_index(op.f('ix_firewall_rules_created_by_id'), 'firewall_rules', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_firewall_rules_deleted_at'), 'firewall_rules', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_firewall_rules_landing_zone'), 'firewall_rules', ['landing_zone'], unique=False)
    op.create_table('approval_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.String(length=255), nullable=True),
    sa.Column('approver_name', sa.String(length=255), nullable=True),
    sa.Column('approver_role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='approvalstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.oidc_sub'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['firewall_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('idx_rule_status', 'approval_records', ['rule_id', 'status'], unique=False)
    op.create_index(op.f('ix_approval_records__version'), 'approval_records', ['_version'], unique=False)
    op.create_index(op.f('ix_approval_records_deleted_at'), 'approval_records', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_approval_records_rule_id'), 'approval_records', ['rule_id'], unique=False)
    op.create_table('rule_approvers',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['firewall_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.oidc_sub'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'user_id')
    )
    op.create_table('rule_tags',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['firewall_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'tag_id')
    )
    op.create_table('tag_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['firewall_rules.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('tag_id', 'rule_id', name='uq_tag_rule')
    )
    op.create_index(op.f('ix_tag_rules__version'), 'tag_rules', ['_version'], unique=False)
    op.create_index(op.f('ix_tag_rules_deleted_at'), 'tag_rules', ['deleted_at'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_rules_deleted_at'), table_name='tag_rules')
    op.drop_index(op.f('ix_tag_rules__version'), table_name='tag_rules')
    op.drop_table('tag_rules')
    op.drop_table('rule_tags')
    op.drop_table('rule_approvers')
    op.drop_index(op.f('ix_approval_records_rule_id'), table_name='approval_records')
    op.drop_index(op.f('ix_approval_records_deleted_at'), table_name='approval_records')
    op.drop_index(op.f('ix_approval_records__version'), table_name='approval_records')
    op.drop_index('idx_rule_status', table_name='approval_records')
    op.drop_table('approval_records')
    op.drop_index(op.f('ix_firewall_rules_landing_zone'), table_name='firewall_rules')
    op.drop_index(op.f('ix_firewall_rules_deleted_at'), table_name='firewall_rules')
    op.drop_index(op.f('ix_firewall_rules_created_by_id'), table_name='firewall_rules')
    op.drop_index(op.f('ix_firewall_rules_approved_by_id'), table_name='firewall_rules')
    op.drop_index(op.f('ix_firewall_rules__version'), table_name='firewall_rules')
    op.drop_index('idx_workload_environment', table_name='firewall_rules')
    op.drop_index('idx_name_status', table_name='firewall_rules')
    op.drop_index('idx_landing_zone_status', table_name='firewall_rules')
    op.drop_table('firewall_rules')
    op.drop_index('ix_users_workload', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index(op.f('ix_users_oidc_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users__version'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_deleted_at'), table_name='tags')
    op.drop_index(op.f('ix_tags__version'), table_name='tags')
    op.drop_index('ix_tag_name', table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index('idx_timestamp', table_name='audit_logs')
    op.drop_index('idx_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('approval_workflows')
    # ### end Alembic commands ###